### ISSUE TITLE
Intro text for tests

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/ssh#11]
The test intro statement "The evaluator shall perform the following test:" should be outside the <testlist> tag rather than inside it so that the intro statement is not indented with the tests. Issue present in FCS_SSHC_EXT.1.2 and FCS_SSHS_EXT.1.2.

 Additionally, an extraneous copy of this statement is present in both FCS_SSHC_EXT.1.7 and FCS_SSHS_EXT.1.7 (there is intro text both inside and outside the <testlist> tag; the text inside should be removed).

**Comment by robertmclemons** [comment]
OBE
