### ISSUE TITLE
Consistency with line spacing

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/ssh#13]
Line spacing between newlines is not consistent between elements. For example, the line breaks in the FCS_SSHC_EXT.1.3 app note have whitespace between them but the lines in FCS_SSHC_EXT.1.4 do not.

In general it is recommended not to enclose block text in <h:p> tags. Instead, unformatted text should be used and <h:p/> should be used as line separators for visual consistency.

**Comment by robertmclemons** [comment]
Fixed in translation.
