### ISSUE TITLE
Presentation of selection-based auditable events

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/ssh#14]
If possible, it is recommended to use a rowspan on the Requirement column so that all events for the same SFR are grouped together rather than repeating the SFR name.

If possible, a <h:p/> separator should be used between rows where there are multiple audit record contents for visual clarity (i.e. additional visual separation between "Reason for failure" and "Non-TOE endpoint of attempted connection (IP Address).

**Comment by robertmclemons** [comment]
The rowspan is too hard. Maybe someday. I hand-jammed a paragraph break, though that should be easy to fix in transforms.
