### ISSUE TITLE
DH groups from RFC8268

### ISSUE THREAD

**Issue by stevegrubb** [commoncriteria/ssh#5]
In FCS_SSHC_EXT.1.6 shouldn't it allow the selection of the new DH groups from RFC8268? From the RFC:

Use a Diffie-Hellman prime modulus of at least 3072 bits.  (For bit sizes as specified in [RFC3526], this would allow for any of group15, group16, group17, group18 to be used.

**Comment by robertmclemons** [comment]
I think this is incorporated now.
